name: Compilar APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    container: kivy/buildozer:latest

    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4

      - name: Arreglar permisos del directorio
        run: |
          git config --global --add safe.directory '*'
          chmod -R a+rwx . || true

      - name: Compilar APK con imagen oficial de Kivy
        run: |
          export ANDROID_ACCEPT_SDK_LICENSE=1
          buildozer android debug

      - name: Subir el APK
        uses: actions/upload-artifact@v4
        with:
          name: detector-balones-apk
          path: bin/*.apk
